# Elasticsearch.conf
# See https://www.elastic.co/guide/en/elasticsearch/reference/1.6/modules.html
# for full documentation

cluster.name: "widukind_cluster"
node.name: widukind_es_master

network.bind_host: 0.0.0.0
network.publish_host: 0.0.0.0
network.host: 0.0.0.0

http.port: 9200
http.max_content_length: 200mb

index.number_of_shards: 1
index.number_of_replicas: 0

path.repo: ["/usr/share/elasticsearch/data/"]
