datashared:
  image: tianon/true
  volumes:
    - ./widukind:/widukind
    - ./tmp:/tmpdir

mongodb:
  image: mongo:3.2.4
  command: mongod --noauth --storageEngine wiredTiger --wiredTigerDirectoryForIndexes --directoryperdb
  volumes:
    - ./mongodb/data:/data/db
  volumes_from:
    - datashared
  privileged: true

redis:
  build: redis-docker
  command: redis-server --appendonly yes
  volumes:
    - ./redis/data:/data
  volumes_from:
    - datashared
  privileged: true

cli:
  build: dlstats
  env_file:
    - ./docker_environ
  links:
    - mongodb:mongodb
    - redis:redis
  volumes_from:
    - datashared
    
web:
  build: widukind-web
  env_file:
    - ./docker_environ
  links:
    - mongodb:mongodb    
    - redis:redis
  ports:
    - "HOST_BIND_WEB:80:8080"
  volumes_from:
    - datashared

api:
  build: widukind-api
  env_file:
    - ./docker_environ
  links:
    - mongodb:mongodb    
    - redis:redis
  ports:
    - "HOST_BIND_API:80:8080"
  volumes_from:
    - datashared
