FROM elasticsearch:1.7.3

RUN /usr/share/elasticsearch/bin/plugin -i royrusso/elasticsearch-HQ
RUN /usr/share/elasticsearch/bin/plugin -i mobz/elasticsearch-head
RUN /usr/share/elasticsearch/bin/plugin -i lmenezes/elasticsearch-kopf/1.O